/**
 * Metric definitions for the TMRW dashboard.
 * Covers the ~30 Tableau metrics plus additional spec-driven KPIs.
 */

import type { MetricDefinition } from '@/lib/types';

export const metricDefinitions: MetricDefinition[] = [
  // ── Financial ──────────────────────────────────────────────────────
  {
    id: 'mrr',
    label: 'Monthly Recurring Revenue',
    description: 'Total MRR from active subscriptions',
    source: 'stripe',
    direction: 'higher-better',
    format: 'currency',
    target: 100_000,
    category: 'financial',
  },
  {
    id: 'total-revenue',
    label: 'Total Revenue',
    description: 'Gross revenue for the period',
    source: 'stripe',
    direction: 'higher-better',
    format: 'currency',
    target: null,
    category: 'financial',
  },
  {
    id: 'subscription-revenue',
    label: 'Subscription Revenue',
    description: 'Revenue from recurring subscriptions',
    source: 'stripe',
    direction: 'higher-better',
    format: 'currency',
    target: null,
    category: 'financial',
  },
  {
    id: 'advanced-testing-revenue',
    label: 'Advanced Testing Revenue',
    description: 'One-time advanced testing collections',
    source: 'stripe',
    direction: 'higher-better',
    format: 'currency',
    target: null,
    category: 'financial',
  },
  {
    id: 'supplement-revenue',
    label: 'Supplement Revenue',
    description: 'Revenue from supplement sales',
    source: 'stripe',
    direction: 'higher-better',
    format: 'currency',
    target: null,
    category: 'financial',
  },
  {
    id: 'add-on-revenue',
    label: 'Add-On Revenue',
    description: 'Revenue from add-on services',
    source: 'stripe',
    direction: 'higher-better',
    format: 'currency',
    target: null,
    category: 'financial',
  },
  {
    id: 'arpu',
    label: 'ARPU',
    description: 'Average revenue per user per month',
    source: 'derived',
    direction: 'higher-better',
    format: 'currency',
    target: null,
    category: 'financial',
  },
  {
    id: 'ltv',
    label: 'Lifetime Value',
    description: 'Estimated customer lifetime value',
    source: 'derived',
    direction: 'higher-better',
    format: 'currency',
    target: null,
    category: 'financial',
  },
  {
    id: 'payment-success-rate',
    label: 'Payment Success Rate',
    description: 'Percentage of payment attempts that succeed',
    source: 'stripe',
    direction: 'higher-better',
    format: 'percentage',
    target: 98,
    category: 'financial',
  },
  {
    id: 'failed-payments',
    label: 'Failed Payments',
    description: 'Count of declined or blocked transactions',
    source: 'stripe',
    direction: 'lower-better',
    format: 'number',
    target: 0,
    category: 'financial',
  },

  // ── Members ────────────────────────────────────────────────────────
  {
    id: 'total-members',
    label: 'Total Members',
    description: 'All registered members',
    source: 'hubspot',
    direction: 'higher-better',
    format: 'number',
    target: null,
    category: 'members',
  },
  {
    id: 'active-members',
    label: 'Active Members',
    description: 'Members with open cases',
    source: 'hubspot',
    direction: 'higher-better',
    format: 'number',
    target: null,
    category: 'members',
  },
  {
    id: 'new-members',
    label: 'New Members',
    description: 'Members registered in the period',
    source: 'hubspot',
    direction: 'higher-better',
    format: 'number',
    target: null,
    category: 'members',
  },
  {
    id: 'churn-rate',
    label: 'Churn Rate',
    description: 'Percentage of members who churned in the period',
    source: 'derived',
    direction: 'lower-better',
    format: 'percentage',
    target: 5,
    category: 'members',
  },
  {
    id: 'net-member-growth',
    label: 'Net Member Growth',
    description: 'New members minus churned members',
    source: 'derived',
    direction: 'higher-better',
    format: 'number',
    target: null,
    category: 'members',
  },
  {
    id: 'health-story-completion-rate',
    label: 'Health Story Completion Rate',
    description: 'Percentage of registered members who completed their health story',
    source: 'hubspot',
    direction: 'higher-better',
    format: 'percentage',
    target: 85,
    category: 'members',
  },
  {
    id: 'kit-return-rate',
    label: 'Kit Return Rate',
    description: 'Percentage of dispatched kits that were returned',
    source: 'hubspot',
    direction: 'higher-better',
    format: 'percentage',
    target: 90,
    category: 'members',
  },
  {
    id: 'dashboard-unlock-rate',
    label: 'Dashboard Unlock Rate',
    description: 'Percentage of members who unlocked their dashboard',
    source: 'hubspot',
    direction: 'higher-better',
    format: 'percentage',
    target: 80,
    category: 'members',
  },
  {
    id: 'avg-days-to-dashboard',
    label: 'Avg Days to Dashboard',
    description: 'Average days from registration to dashboard unlock',
    source: 'derived',
    direction: 'lower-better',
    format: 'days',
    target: 30,
    category: 'members',
  },
  {
    id: 'retest-rate',
    label: 'Retest Rate',
    description: 'Percentage of eligible members who completed retests',
    source: 'hubspot',
    direction: 'higher-better',
    format: 'percentage',
    target: 70,
    category: 'members',
  },
  {
    id: 'stalled-members',
    label: 'Stalled Members',
    description: 'Members with no journey progress in 14+ days',
    source: 'derived',
    direction: 'lower-better',
    format: 'number',
    target: 0,
    category: 'members',
  },
  {
    id: 'at-risk-members',
    label: 'At-Risk Members',
    description: 'Members flagged as at-risk of churning',
    source: 'derived',
    direction: 'lower-better',
    format: 'number',
    target: 0,
    category: 'members',
  },

  // ── Clinical ───────────────────────────────────────────────────────
  {
    id: 'insights-calls-completed',
    label: 'Insights Calls Completed',
    description: 'Number of insights calls completed in the period',
    source: 'hubspot',
    direction: 'higher-better',
    format: 'number',
    target: null,
    category: 'clinical',
  },
  {
    id: 'avg-days-to-insights-call',
    label: 'Avg Days to Insights Call',
    description: 'Average days from dashboard unlock to insights call',
    source: 'derived',
    direction: 'lower-better',
    format: 'days',
    target: 14,
    category: 'clinical',
  },
  {
    id: 'clinician-utilisation',
    label: 'Clinician Utilisation',
    description: 'Percentage of clinician capacity used',
    source: 'derived',
    direction: 'higher-better',
    format: 'percentage',
    target: 80,
    category: 'clinical',
  },
  {
    id: 'active-plans',
    label: 'Active Plans',
    description: 'Members currently on an active health plan',
    source: 'hubspot',
    direction: 'higher-better',
    format: 'number',
    target: null,
    category: 'clinical',
  },
  {
    id: 'better-tomorrows-avg',
    label: 'Better Tomorrows (Avg)',
    description: 'Average Better Tomorrows score across members',
    source: 'derived',
    direction: 'higher-better',
    format: 'number',
    target: null,
    category: 'clinical',
  },

  // ── Support ────────────────────────────────────────────────────────
  {
    id: 'open-tickets',
    label: 'Open Tickets',
    description: 'Currently open support tickets',
    source: 'zendesk',
    direction: 'lower-better',
    format: 'number',
    target: null,
    category: 'support',
  },
  {
    id: 'new-tickets',
    label: 'New Tickets',
    description: 'Tickets created in the period',
    source: 'zendesk',
    direction: 'lower-better',
    format: 'number',
    target: null,
    category: 'support',
  },
  {
    id: 'first-reply-time',
    label: 'First Reply Time',
    description: 'Average time to first agent reply (minutes)',
    source: 'zendesk',
    direction: 'lower-better',
    format: 'hours',
    target: 60,
    category: 'support',
  },
  {
    id: 'resolution-time',
    label: 'Resolution Time',
    description: 'Average full resolution time (minutes)',
    source: 'zendesk',
    direction: 'lower-better',
    format: 'hours',
    target: 480,
    category: 'support',
  },
  {
    id: 'csat-score',
    label: 'CSAT Score',
    description: 'Customer satisfaction score (% good)',
    source: 'zendesk',
    direction: 'higher-better',
    format: 'percentage',
    target: 90,
    category: 'support',
  },
  {
    id: 'ticket-backlog',
    label: 'Ticket Backlog',
    description: 'Tickets open longer than SLA threshold',
    source: 'derived',
    direction: 'lower-better',
    format: 'number',
    target: 0,
    category: 'support',
  },
  {
    id: 'one-touch-resolution-rate',
    label: 'One-Touch Resolution Rate',
    description: 'Percentage of tickets resolved in a single reply',
    source: 'zendesk',
    direction: 'higher-better',
    format: 'percentage',
    target: 50,
    category: 'support',
  },
  {
    id: 'ticket-reopens',
    label: 'Ticket Reopens',
    description: 'Tickets reopened after being solved',
    source: 'zendesk',
    direction: 'lower-better',
    format: 'number',
    target: 0,
    category: 'support',
  },

  // ── Marketing ──────────────────────────────────────────────────────
  {
    id: 'leads',
    label: 'Leads',
    description: 'New marketing leads generated in the period',
    source: 'hubspot',
    direction: 'higher-better',
    format: 'number',
    target: null,
    category: 'marketing',
  },
  {
    id: 'lead-conversion-rate',
    label: 'Lead Conversion Rate',
    description: 'Percentage of leads that converted to members',
    source: 'derived',
    direction: 'higher-better',
    format: 'percentage',
    target: 15,
    category: 'marketing',
  },
  {
    id: 'cac',
    label: 'Customer Acquisition Cost',
    description: 'Average cost to acquire a new member',
    source: 'manual',
    direction: 'lower-better',
    format: 'currency',
    target: null,
    category: 'marketing',
  },
  {
    id: 'email-sequences-triggered',
    label: 'Email Sequences Triggered',
    description: 'Automated email sequences fired in the period',
    source: 'hubspot',
    direction: 'higher-better',
    format: 'number',
    target: null,
    category: 'marketing',
  },
];

/**
 * Lookup a single metric definition by id.
 */
export function getMetric(id: string): MetricDefinition | undefined {
  return metricDefinitions.find((m) => m.id === id);
}

/**
 * Get all metric definitions for a given category.
 */
export function getMetricsByCategory(category: string): MetricDefinition[] {
  return metricDefinitions.filter((m) => m.category === category);
}
